#Cargo.toml
[package]
name = "ClearApp"
version = "0.1.0"
edition = "2024"

[dependencies]
slint = { version = "1.14", features = ["backend-winit", "renderer-skia"] }

[build-dependencies]
slint-build = "1.14"