#Cargo.toml

[package]
name = "ClearApp"
version = "0.1.0"
edition = "2024"

[dependencies]
slint = { version = "1.15", features = ["backend-winit", "renderer-skia"] }
#slint = { version = "1.15", features = ["backend-qt", "renderer-skia"] }

serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = "0.4"
self_update = "0.42"

[build-dependencies]
slint-build = "1.15"