[dist]
cargo-dist-version = "0.30.3"

# только Windows
targets = ["x86_64-pc-windows-msvc"]

# installer
installers = ["msi"]

# updater включён
windows-archive = "zip"

# GitHub Releases
ci = ["github"]

# автообновление
update-strategy = "release"

# имя бинаря
bin-name = "ClearApp"
